
openapi: 3.0.0
info:
  title: Jira Issue Search
  version: 1.0.0
servers:
  - url: https://aiinkwell-team.atlassian.net/rest/api/3
paths:
  /search:
    get:
      summary: Search Jira issues
      parameters:
        - in: query
          name: jql
          required: true
          schema:
            type: string
          description: The Jira Query Language to filter issues
      responses:
        '200':
          description: List of issues
          content:
            application/json:
              schema:
                type: object
